### ISSUE TITLE
🐛 Update `updated_at` in mappings

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#111]
## Describe the bug
Error log reported by @henro001: 
```
"stacktrace": ["org.elasticsearch.transport.RemoteTransportException: [workflow-es-data-4][10.233.81.26:9300][indices:data/read/search[phase/query]]",
"Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [updated_at] in order to sort on"
```

From the indicies:
```
{"type": "server", "timestamp": "2021-03-15T15:57:16,916Z", "level": "DEBUG", "component": "o.e.a.s.TransportSearchAction", "cluster.name": "workflow", "node.name": "workflow-es-data-5", "message": "[file_centric_1.0][2], node[AghrzU6WQDO-rZTrDgqkWQ], [R], s[STARTED], a[id=XhDFAA7FQ86ctbOyhFazsQ]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[analysis_centric, analysis_centric_1.0, file_centric, file_centric_1.0, task, task-20200923, workflow, workflow-20200923], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false, ignore_throttled=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=0, batchedReduceSize=512, preFilterShardSize=42, allowPartialSearchResults=true, localClusterAlias=null, getOrCreateAbsoluteStartMillis=-1, ccsMinimizeRoundtrips=true, source={\"query\":{\"bool\":{\"must\":[{\"term\":{\"analysis_id\":{\"value\":\"e3b4cdf3-a644-47a2-b4cd-f3a64447a2a2\",\"boost\":1.0}}}],\"adjust_pure_negative\":true,\"boost\":1.0}},\"sort\":[{\"updated_at\":{\"order\":\"asc\"}}]}}] lastShard [true]", "cluster.uuid": "6nSVxZP7SiG5swH9g0AFjA", "node.id": "fEOpLy3gQpGYVqMs0l1NKg" ,
```

## Expected behaviour
- [ ]  updated the mappings in the `file centric` and `analysis centric` mappings to repo to reflect the new fields

**Comment by jaserud** [comment]
Maestro already has `updated_at` for file_centric and analysis_centric:
https://github.com/overture-stack/maestro/blob/7f3388a10bc9e280952cc27fb450c7314b76118c/maestro-app/src/main/resources/analysis_centric.json#L79
https://github.com/overture-stack/maestro/blob/029187d6f54b082d74e0e28516aaaa767e23c233/maestro-app/src/main/resources/file_centric.json#L106

And I have verified these are the mappings in use in dev and qa.

| env | file_centric | analysis_centric |
| ------------- |:-------------:| -----:|
| DEV | ![image](https://user-images.githubusercontent.com/34698315/112014266-18aab180-8b01-11eb-98e8-c4b170715166.png)|![image](https://user-images.githubusercontent.com/34698315/112014365-31b36280-8b01-11eb-961e-31ec5f31e759.png)|
| QA | ![image](https://user-images.githubusercontent.com/34698315/112014555-645d5b00-8b01-11eb-8ba9-a438d37ca30b.png)|![image](https://user-images.githubusercontent.com/34698315/112014496-51e32180-8b01-11eb-9e89-5e68f62299e9.png)|

I can't see the mapping in use in prod but it must contain updated_at (at least for analysis_centric) because we are able to sort by updadedAt on analysis with no error:
![image](https://user-images.githubusercontent.com/34698315/112018081-a20fb300-8b04-11eb-8f59-52770d638ec0.png)

Also song-search is already set to convert values from es from snake-case:
https://github.com/icgc-argo/song-search/blob/24842f7c12accae88777bf093b332b346ccaae7e/src/main/java/bio/overture/songsearch/model/Analysis.java#L34

**Comment by andricDu** [comment]
follow up on this

**Comment by andricDu** [comment]
I've confirmed that the mappings for file-centric and analysis-centric in prod have the updated_at date field in their mappings.
