### ISSUE TITLE
Prepare for May data release - QC LUCA-KR, PACA-CA, PTC-SA

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/workflow-roadmap#112]
For every donor we have alignment, we need to ensure we have a successful Sanger and Mutect calls. Will involve coordination with Rosi. 

<<We can list our target data-set for the Data Release 3.0 here if we know ahead of time>>

- [x] QC all the analysis and suppress failed/duplicated run output analysis
- [x] Get the numbers for donor/alignment/sanger/mutect2

**Comment by lindaxiang** [comment]
Here is one PTC-SA failed sanger-wxs run, I will go to suppress the output analysis

**studyId**|**donorId**|**sampleId**|**tumourNormalDesignation**|**experimental\_strategy**|**input\_analysisId**|**input\_analysisType**|**latest\_complete\_time**|**runId**|**complete\_time**|**output\_analysis\_to\_suppress**|**reason**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
PTC-SA|DO234005|SA607379|Tumour|WXS|4e59d784-8604-43d4-99d7-84860473d433|sequencing\_alignment| |wes-432d7e2dc404405c9e3559924b94ae4c|2021-01-30 02:53:44|['c5064664-8ad4-48c4-8646-648ad408c468']|failed\_run\_output\_analysis

**Comment by lindaxiang** [comment]
Suppress the above `output_analysis_to_suppress`

**Comment by lindaxiang** [comment]
Here is the table summarize the current counts generated directly from SONG for donor/aln/variantCalls:

**Project**|**Experiment**|**#Donor**|**#Total\_Aln**|**#Normal\_Aln**|**#Tumour\_Aln**|**#Sanger\_Call**|**#Mutect2\_Call**|**QA dashboard**|**Staging File Repo**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
PACA-CA|WGS|132|285|133|152|152|152|Match| Mismatch for #Donor, #Tumour_Aln
PACA-CA|WXS|28|60|28|32|32|32|Match|Mismatch for #Donor, #Normal_Aln, #Tumour_Aln
LUCA-KR|WGS|29|58|29|29|29|29|Match|Mismatch for #Donor, #Normal_Aln
LUCA-KR|WXS|130|260|130|130|130|130|Match|Mismatch for #Donor, #Normal_Aln
PTC-SA|WXS|239|478|239|239|239|239|Match|Mismatch for all numbers except #Sanger_Call

**Note**:  
- The numbers in the above table EXCLUDE the donors which miss alignment for either normal or tumour, or any variant calls
- The fix for `Mismatch` just need to add the rules: ONLY release the donor with ALN + Sanger + Mutect2 
- ideally #Sanger_Calls = #Mutect2_Calls = #Tumour_Aln
- PACA-CA has donors which have multi-normals and multi-tumours

**The Donors to be excluded from May release**:
- **PACA-CA WGS**:

Donor | Status | Issue | Note | Action
-- | -- | -- | -- | --
DO35226 | Has two Tumour Alns but not Normal Aln | | Has data in Current Release. The same donor has WXS data | [DO35226.wgs.exclude_analysisId.txt](https://github.com/icgc-argo/workflow-roadmap/files/6435495/DO35226.wgs.exclude_analysisId.txt)



- **PACA-CA WXS**: #Tumour_Aln > #Sanger_Calls = #Mutect2_Calls 

Donor | Status | Issue | Note | Action
-- | -- | -- | -- | --
DO35140 | Has two Tumour Alns but missing Normal Aln | | The same donor has WGS data. WXS share one same tumour sample with WGS| [DO35140.wxs.exclude_analysisId.txt](https://github.com/icgc-argo/workflow-roadmap/files/6435504/DO35140.wxs.exclude_analysisId.txt)
DO35158 | Missing Sanger and Mutect2 | https://github.com/icgc-argo/workflow-roadmap/issues/94 | |Exclude donor

- **LUCA-KR WGS**:

Donor | Status | Issue | Action
-- | -- | -- | --
DO224624 | Missing Tumour Aln | | Exclude donor

- **LUCA-KR WXS**:

Donor | Status | Issue | Action
-- | -- | -- | --
DO52372 | Missing Tumour Aln | | Exclude donor
DO52374 | Missing Tumour Aln | | Exclude donor

- **PTC-SA WXS**: #Tumour_Aln > #Mutect2_Calls >#Sanger_Calls 

**Donor**|**Status**|**Issue**|**Note**|**Action**
:-----:|:-----:|:-----:|:-----:|:-----:
DO234005|Missing Sanger|https://github.com/icgc-argo/workflow-roadmap/issues/95|May have data issue. | Exclude donor
DO231493|Missing Sanger and Mutect2| https://github.com/icgc-argo/workflow-roadmap/issues/29|May have data issue.| Exclude donor
DO231311|Missing Sanger and Mutect2| https://github.com/icgc-argo/workflow-roadmap/issues/29|May have data issue. | Exclude donor

**Comment by hknahal** [comment]
The LUCA-KR donors listed above may be resolved once the EGA->Collab transfer is complete: https://github.com/icgc-argo/ega-file-transfer/issues/10 Currently transferring these files from EGA to Collab.
