### ISSUE TITLE
Workflow Runs stuck at `sangerWgs` although the task has already completed 

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#149]
## Detailed Description
The `sangeWgs` task has completed but the next task did NOT get kicked off. The job status is stuck at running at task `sangerWgs`. 

## List all runids affected

**run\_id**|**sangeWgs\_task\_end**
:-----:|:-----:
wes-55291f579a65435898f8462c870f5081|Workflow end: Tue May  4 03:08:07 UTC 2021
wes-6242b2175a0f4929936a221de512b303|Workflow end: Mon May  3 15:02:42 UTC 2021
wes-b0a74dd399fb43218fcaaa05b24245b4|Workflow end: Wed May  5 02:10:17 UTC 2021
wes-9adceb55608d4133ad3f9e1260499f59|Workflow end: Tue May  4 18:44:39 UTC 2021
wes-559df09596e54e06af042fd47ab6d2b5|Workflow end: Wed May  5 07:36:49 UTC 2021
wes-0f0b733a0e83411a9b6c725346a15611|Workflow end: Thu May  6 01:45:37 UTC 2021

## Exit criteria
- [ ] Issue has been resolved
- [ ] Run is resumed

**Comment by rosibaj** [comment]
on hold until collab is back up and running

**Comment by lepsalex** [comment]
@rosibaj @lindaxiang as noted in slack, the executor pods for these runs were simply unable to schedule the next task pod children, and have since disappeared, earning them the moniker "the missing six". We have their logs from right up until the time of their presupposed vanishing, @henro001 will need to cross reference against the Kubernetes API usage statistics to see if these ghostly happenings can be attributed to same cause as the other issues from this time or if we have a fresh mystery on our hands.
