### ISSUE TITLE
Workflow Run Failure -OCCAMS-GB jobs related to ID changes

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#160]
There are some discrepancies between SONG Id information at:
https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/all
and
https://song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/all

For the donors/samples in the attached file. 
[OCCAMS-GB.id-issue.txt](https://github.com/icgc-argo/workflow-roadmap/files/6687472/OCCAMS-GB.id-issue.txt)

**Comment by rosibaj** [comment]
Analysis June 21, 2021

## History

- ESAD-UK/OCCAMS-GB ids were renamed due to an ICGC25K release issue with sensitive ids: https://github.com/icgc-argo/ega-file-transfer/issues/1.  This was confirmed to be done in February. 
- Hardeep updated the suppressed analysis with the updated ids here: https://github.com/icgc-argo/workflow-roadmap/issues/97 

## Single Job analysis 
- Job id: https://wes.rdpc.cancercollaboratory.org/runs/wes-e29e470b89db480eb0398092b335d17f 
- Song analysis input: 
  - https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/9294356b-4dd0-43f9-9435-6b4dd0c3f9bc' 
- The analysis was confirmed to DOWNLOAD not RESUME. 
- This command was used to submit and anlaysis id with thie resulting error: `sing submit -f 4fdd3b0e-61f1-473b-b8f1-8502c5f8ce75.dna_alignment.payload.json | jq -er .analysisId | tr -d '\n'`
  - SONG_SERVER_ERROR[sample.to.specimen.id.mismatch @ 1624164812687]: 
  - [CompositeEntityService::sample.to.specimen.id.mismatch] - Existing sample (submitterSampleId='LP6005409-DNA_G02') has submitterSpecimenId='TB11-1916-GOJT1', but this submission says it has submitterSpecimenId='32f4170cc4da08e9e4b3119374fe2dabaa34c1acc30c99225c2a0032a5cfa970' instead. 
- The sample portion of the submitted analysis looks like this, and has the correct/expected ids: 
```
  "samples": [
    {
      "submitterSampleId": "LP6005409-DNA_G02",
      "sampleType": "Total DNA",
      "matchedNormalSubmitterSampleId": "LP6005408-DNA_G02",
      "specimen": {
        "submitterSpecimenId": "32f4170cc4da08e9e4b3119374fe2dabaa34c1acc30c99225c2a0032a5cfa970",
        "tumourNormalDesignation": "Tumour",
        "specimenTissueSource": "Solid tissue",
        "specimenType": "Primary tumour"
      },
      "donor": {
        "submitterDonorId": "ede9d5169929a219ad3172388cff1c027c414717341449633414330b85746bd4",
        "gender": "Male"
      }
    }
  ]
```
- looking in clinical document `"_id": "5ed6984657eed70007eacd70",`, the DONOR/SAMPLE/SPECIMEN/SAMPLE submitter ids in the alignment payload above and the original analysis line up as expected. 
- clinical endpoints return the expected donorids from this 
- clinical has no entry/concept of `TB11-1916-GOJT1`, which Song thinks sample `LP6005409-DNA_G02` is registered to

## To be discussed with Jon
- Why does RDPC prod SONG have this record of the wrong specimen-id--> sample id hierarchy? 
- this is one example only; there are multiple cases of this.

**Comment by rosibaj** [comment]
- update suppressed analysis-ids from the old ids to new ids 
- provide again the mapping of old to new donor/specimen-ids
- confirm with @andricDu if the Song cache clears on restart.

**Comment by rosibaj** [comment]
## Resources
- This is the list of analysis-ids to be changed (column 1) :  [OCCAMS-GB_rename_issue_analysisId.txt](https://github.com/icgc-argo/workflow-roadmap/files/6694971/OCCAMS-GB_rename_issue_analysisId.txt)
- This is the mapping file of `old` ESAD-UK ids to `new` OCCAMS-GB  ids : https://docs.google.com/spreadsheets/d/1TtXr_BIv7M_BwCugxixqRP4SUoElntmxDskCn4eK4J0/edit#gid=1256054450
- Song URL: https://song.rdpc.cancercollaboratory.org

## Task 
- [ ]  Replace the ids in the above suppressed analyses with the correct `new` ids, in the production Song instance. 
- verified with dusan there is no cache; only th ids relations in db. if that is taken care of, then song + clinical should work 

## Timing
- if song is down while this is happening, wfs interrupted can be resume from download/upload step

**Comment by lindaxiang** [comment]
Completed.
