### ISSUE TITLE
ICGC25K Transfer to Azure: Transfers greater than 200GB are failing 

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/workflow-roadmap#171]

**Comment by akachru-github** [comment]
Issue:
- Final portion fo the workflow uploads the last "part" forever.

**Comment by andricDu** [comment]
Testing new snapshot version `d23f76c` 

This contains an updated version of the azure storage dependency.

**Comment by andricDu** [comment]
Currently testing a new fix. 

Fix is in the client code. Server version is 7fc9bb0.

Even with the update in the sdk, we are still relying on a "legacy" Storage SDK rather than the full Azure SDK. With this legacy SDK there are some extra options for overriding the default block size, but they are not referred to as such.

Currently testing the method call `setStreamWriteSizeInBytes` to see if this will be the secret sauce we are missing.
I'm hopeful as the default value inside the blob client appeared to be around 4MB which was what I had suspected was the case all along.

I also enabled debug logging in the score client and intercepted the put requests to Azure and found that content length was the default 4MB. Will update ticket once testing finishes.
