### ISSUE TITLE
Migrate one pilot workflow to the new Github Org

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/workflow-roadmap#174]
- As a result of this migration generate a wiki SOP to document the step by step process and any challenges faced. Once completed, we can use this SOP to have multiple parallel migrations executed by multiple team members. 
  - Some packages are shared between workflows. We will need to consider how to handle this complexity as a part of this ticket. 
  - Target is to make this a no impact migration. 

note the parent epic ticket is here: #153

**Comment by junjun-zhang** [comment]
Did a pre-pilot using two demo repositories of WFPM packages from https://github.com/ICGC-TCGA-PanCancer to https://github.com/icgc-argo-workflows, it turns out to be much simpler than I thougtht. Follow the these steps, it will have no impact as a result of the repository transfer:

1. Transfer repository from old org to new org
2. Fork the same repo from new org back to old org
3. Add archive note in README.md and commit to old org and archive the repo (and keep it forever). The archive note could look like this: https://github.com/ICGC-TCGA-PanCancer/demo-pkgs1#readme
4. no work needed for docker registries, at this point the same workflow can be run from both old and new repo

Note: repository transfer to new organization does not affect docker images built at the old organization, which is the reason everything still works for both new org repo and old org repo (which is a fork of the new) since they are still pointing to the unchanged docker images.

Next step is to start the polit transfer by followinng the above process to transfer repos related to the DNA-Seq process workflow:
- dna-seq-processing-wfs
- nextflow-data-processing-utility-tools
- data-processing-utility-tools
- dna-seq-processing-tools
- data-qc-tools-and-wfs
- gatk-tools

**Comment by junjun-zhang** [comment]
Although running the workflow (from the old repo or the new repo) is not affected, after some discussion with @lindaxiang we realized that the wfpm packages at the new repo will not be importable using the previous package's URI. Importing the wfpm packages from the old repo is not possible either as the package assets will not be created when fork back the repo back to the old org. Here is an example: https://github.com/ICGC-TCGA-PanCancer/demo-pkgs1/releases/tag/demo-fastqc1.v0.1.0. We would need to re-create the releases (with wfpm package assets attached) after forking back the repo.

**Comment by junjun-zhang** [comment]
this is done, details: https://github.com/icgc-argo-workflows/workflow-repo-migration
