### ISSUE TITLE
ICGC25K Azure Transfer: Submission step fails which results in an endless retry loop

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/workflow-roadmap#181]

**Comment by junjun-zhang** [comment]
This happened in jobs with 50 analysis objects. For a while these type of jobs were ok, but at some point there were some failure with some of the song analysis object upload. Due to auto-retry (max 3 retries per analysis object) and fairly large number of failure, the compounding effect was too many (seemingly infinite) retries.

Anyhow, the easiest fix is to delete these jobs, and regenerate new jobs to cover the same SONG analysis objects but with each job for only one analysis object. Then start running the new jobs.

Care need to be paid how to regenerate new jobs so no jobs will be duplicated or missed. @lindaxiang we can chat more on details.

**Comment by akachru-github** [comment]
The workaround as Junjun suggested would be to reschedule these jobs. Keeping ticket open until the jobs are successfully published.

**Comment by akachru-github** [comment]
All data was published. Closing.
