### ISSUE TITLE
Supporting APGI-AU for data submission

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#233]

**Comment by lindaxiang** [comment]
- Sample registration table has mismatched information with what are in ICGC legacy portal for field "specimenTissueSource". Need to confirm with the data submitter. 
- Here is current sample registration table in Prod. 
[sample_registration_APGI-AU_20220316.txt](https://github.com/icgc-argo/workflow-roadmap/files/8262425/sample_registration_APGI-AU_20220316.txt)

**Comment by lindaxiang** [comment]
The program has confirmed that "specimenTissueSource" should be "Solid tissue" instead of "Other".
That means we need to update the clinical database for field: `specimen_tissue_source` accordingly.

**Comment by b-f-chan** [comment]
Re-assigning to @hknahal - Held off on this due to specimen conflict, but turned into another issue with mysterious samples (might need another ticket for this)

@hknahal to create separate ticket for mysterious sample issue - 50 donors that Amber does not recall uploading, troubleshooting has not turned up root cause, so need separate investigation.  Waiting for Amber to confirm whether we can just remove them.

**Comment by b-f-chan** [comment]
@hknahal reviewed with @joneubank last week - Just need to reconfirm these 50 donors still have issues, if so, @joneubank will have to do a manual backend update
