### ISSUE TITLE
Supporting POG-CA for data submission

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#235]
Current status
- one case with normal/tumour samples registered
- There was an error in the data for the normal sample P02374, the submitter_specimen_id should be 38119-PB-P02374 instead of 38119-OCT-1-P02374
- Tumour sample has molecular data submitted and published

**Comment by b-f-chan** [comment]
Move back to Ready to Implement, as it is blocked/waiting the SOPs being written (jon)

POG-CA they are and have actively done submissions, so getting the SOP is important

**Comment by hknahal** [comment]
Following SOP for removing samples: https://wiki.oicr.on.ca/pages/viewpage.action?pageId=150638363

- [ ] No clinical data has been submitted
- [ ] No active sample registration/clinical submission

Steps:

1. Do 'dry-run' of deletion of registered sample ID "P02374" using DELETE sample endpoint (DELETE /submission/program/{program_id}/registration/unregister)
```
curl -X 'DELETE' \
  'https://clinical.platform.icgc-argo.org/submission/program/POG-CA/registration/unregister?dryRun=true&sampleSubmitterIds=P02374' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer my_ego_token'
```
Result:
```
{
  "dryRun": true,
  "samplesDeleted": [
    "P02374"
  ],
  "specimensDeleted": [
    "38119-OCT-1-P02374"
  ],
  "donorsDeleted": []
}
```

This deletes the affected submitter_specimen_id "38119-OCT-1-P02374" as well without deleting the donor ID.

2. Do actual deletion using same DELETE sample endpoint (without 'dry-run'):
```
curl -X 'DELETE' \
  'https://clinical.platform.icgc-argo.org/submission/program/POG-CA/registration/unregister?dryRun=false&sampleSubmitterIds=P02374' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer my_ego_token'
```

Result:
```
{
  "dryRun": false,
  "samplesDeleted": [
    "P02374"
  ],
  "specimensDeleted": [
    "38119-OCT-1-P02374"
  ],
  "donorsDeleted": []
}
```

2. Confirm change is reflected in Program Dashboard:
![pog-ca_sample_removed](https://user-images.githubusercontent.com/4992044/174891288-d721166c-bed0-486d-901b-db534a5617a9.png)

4. No analysis ID found in RDPC for submitter_sample_id "P02374" because normal file has not been uploaded yet, so no need to suppress analysis:

POG-CA program can re-submit correct submitter_specimen_id and associated submitter_sample_id.

**Comment by hknahal** [comment]
This ticket is done. Followed up with Young Cheng and Jessica Nelson regarding completion of their request to remove the incorrect submitter_specimen_id.

**Comment by b-f-chan** [comment]
Already completed, @hknahal executed using the new SOP, closing
