### ISSUE TITLE
`DO252119` donor deleted but still exists in SONG

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#303]
Following discussion with Steve:
https://extsd.oicr.on.ca/browse/ARGOHD-264

Steve uploaded files to `DO252119` when it should have been `DO252193`.

`DO252119` was deleted as a part of tickets: 
https://github.com/icgc-argo/workflow-roadmap/issues/286
https://github.com/icgc-argo/workflow-roadmap/issues/291
https://github.com/icgc-argo/workflow-roadmap/issues/294

Still exists in `SONG` but not in `clinical.SONG`.

- [ ] Inform Steve to submit to correct donor
- [ ] Suppress ongoing analysis in `DO252119`
- [ ] Re-attempt deletion?

**Comment by hknahal** [comment]
Table with ID discrepancies: https://docs.google.com/spreadsheets/d/1wFY8m_mMrNAj7zUcREHaN9X08QAGTYwrBEt7vSG9w0U/edit?usp=sharing

Jon manually updated the old/new IDs for the donor/specimen/sample, so they show correctly in submission-song now.

**Comment by hknahal** [comment]
Donor `DO252193` has several duplicated analyses for both the tumour and normal specimen: [duplicated_analyses.txt](https://github.com/icgc-argo/workflow-roadmap/files/10483901/duplicated_analyses.txt)

However the Program Dashboard does not show this:
![DO252193](https://user-images.githubusercontent.com/4992044/214158401-e06c7362-a253-4224-adf0-5574263012a9.png)

Normally updates to SONG done through the API result in Maestro automatically updating the song-search index in RDPC. However, in this case since we manually updated the data directly, we'll need to get Maestro to re-index the study in RDPC.

**Comment by joneubank** [comment]
Note for future reference: when individual analyses need to be re-indexed in RDPC we can shortcut this by running unpublish then publish actions on them in song.  For this case I am reindexing with maestro to ensure everything gets updated.
