### ISSUE TITLE
Import LUCA-KR and PACA-CA whole exome payloads to intemediate-song

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/workflow-roadmap#64]
The following whole exome payloads are ready to be imported into intermediate-song:

LUCA-KR (137 donors): https://github.com/icgc-argo/argo-meta/tree/master/icgc_song_payloads/LUCA-KR/WXS/batch2
PACA-CA (13 donors): https://github.com/icgc-argo/argo-meta/tree/master/icgc_song_payloads/PACA-CA/WXS/batch2

Instructions: 
https://wiki.oicr.on.ca/display/icgcargotech/Importing+Legacy+ICGC+objects+into+Intermediate-Song

**Comment by akachru-github** [comment]
Confirmed the following with @joneubank :
- We modified the icgc import to be repeatable for cases where new ids need to be added, allows the export/import process to work on a study/program that was previously imported. 
- These changes were done in Clinical, which will need to be deployed into production in order to support this import. 
- The changes in made in Clinical to support this import are currently deployed to the QA environment.

**Comment by rosibaj** [comment]
- verify if the Batch 2 duplicate information 
- @hknahal is off today, but can help double check the batches when she is back 
- same sample is WGS/WXS.  Could be an error in the intermediate-song import 

1) investigate errors that are happening. 
2) try in QA now that we have a cloned state to verify what is happening in production.

**Comment by joneubank** [comment]
Imported into QA and Prod (not dev cause I was told not to touch dev cause of Junjun work).

**Comment by rosibaj** [comment]
@hknahal Can you please double check the import of batch 2 in prod?

**Comment by hknahal** [comment]
@rosibaj I confirmed the import of the PACA-CA and LUCA-KR batch2 WXS data looks good. I generated the worksheet data for both batches so I can add it to the `Align-Prod-WXS` sheet in https://docs.google.com/spreadsheets/d/13uxLJEjv5m6Q4nNOAsgeIKs8gm2rMctBK2CDXL5c4lU/edit?usp=sharing whenever we're ready.

**Comment by rosibaj** [comment]
thanks @hknahal ! 

and thank you @joneubank for the hard work!!
