### ISSUE TITLE
Shift compute from QA to Dev temporarily

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#72]
- need to test some things in dev.  need more resources for dev to try this 
- would be for benchmarking effort then reverted later. 
- need to test empty-dir in DEV with an alignment large enough to use the scratch space

**Comment by akachru-github** [comment]
- RDPC DEV and QA are in two namespaces in the same cluster
- They share a pool of resources. The resources are dynamically allocated based on activity in the namespaces
- No shifting needed. RDPC DEV has access to the same resources as RDPC QA. 

Do we need to shift resources from RDPC PROD instead to make the testing in RDPC DEV, QA to make the emptyDir testing more meaningful? It's worth pointing out that the hardware on production is much beefier than the RDPC QA / DEV cluster. 
@lepsalex , @junjun-zhang

**Comment by junjun-zhang** [comment]
there are two levels of testing: 1) verify **mechanically** everything still works after deploying and enabling `emptyDir`; 2) verify the actual gain of the performance.

for 1) it can/should be done in QA/DEV, and only move on when verified; for 2) QA may give us some information about performance gain, but ultimately should be done on PROD. Good thing is that the optimization does not affect scientific result.

**Comment by akachru-github** [comment]
So if I understand this right: 
- The testing in DEV/QA will be **functional / mechanical** testing, with just some indication of perf gain. But ultimately, we will need to do a test in production to truly measure what the perf gain of emptyDir will be.

In this case, we probably do not need to make any resources changes in QA/DEV correct?
cc. @yalturmes , @henro001 , @andricDu

**Comment by akachru-github** [comment]
Benchmarking notes:
- We will test in QA/DEV as we need to know whether emptyDir provides any sort of improvement before moving to production. 
- Find BAM with many lanes. Run in DEV with emptydir enabled (**with NO parallel runs in QA**). After this, run same BAM in DEV with Emptydir disabled (**with NO parallel runs in QA**)
- Can do a 4x4 test using the same BAM.
- Confirm RDPC QA/DEV cluster resources : **RDPC dev/qa: 9 x c1.xlarge - 15 cores 128 GB RAM** 
- May need to shift resources from prod to QA/DEV is the comparison turns out to be very close, or only a moderate improvement. 
- Ensure scientific results are not altered when emptydir is enabled. 
- SSD's in prod are gravvy.

No resource shifting need right now. Will close this ticket.
